### ISSUE TITLE
RFC: Renaming the Project Layer

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Helix.Docs#24]
There is some desire in the community to rename the Project layer due to confusion with Visual Studio projects. Ideas include:

* Site
* Tenant
* Context

Doing this will need to be weighed against the documentation updates it will require, community confusion it may create, and upgrade headaches from item and folder renames.

Is this needed, and is it worth it?

**Comment by chorpo** [comment]
Tenant is definetely not better name if you think about what tenant means within SXA context. That would be really confusing - deploying tenant layer into SXA site. Tenant is too narrow as in Project layer you can have different channel outputs not only webSites. Context is on the other hand too general :) I can think of "Channel" as a new name for this layer but I haven't think it through. Will try to come up with better name soon :) I also somehow get used to "Project" meanwhile so I am also fine sticking to this name for now...

**Comment by asmagin** [comment]
Taking in account alphabetical order of configuration processing, I would suggest to select something like *site*. I'm home, channel is to high-level, web is anyway the primary one.

Going even further with application order, *feature* is going to be applied before *foundation*, which doesn't make sense.

However, changes in documentation and various build processes, templates is significant. So I would wait for many likes to appear here.

**Comment by trnktms** [comment]
The Helix structure looks like a tree so, the *Leaf* as a name came in mind as they are the end of the tree. If I go further the other layers could be also renamed and follow alphabetic order:
* *Bole* - Foundation
* *Bought* - Feature
* *Leaf* - Project

**Comment by TwentyGotoTen** [comment]
Sorry I don't have any better ideas, but:
'Context' would have been an ideal candidate, except ... y'know ... Sitecore.
'Site' seems too restrictive, I have Project layer modules that encompass multiple sites. Same potential issue with 'Tenant'

**Comment by dthunziker** [comment]
Sorry to be the only one to -1 until now. While “Project” is not great, I feel it serves its purpose well and it’s generic enough to avoid the Tenant v.s. Site confusion. I have never heard the argument that “Project” conflicts with VS nomenclature - I refer to them as Helix Modules.

**Comment by lakesol** [comment]
Not sure this add great value and the proposed alternatives can also lead to confusion.

Site - As has already been pointed out, come project projects hold logic spanning multiple sites
Tenant - Same as above, just a slightly different cross-cut of the terminology concerns
Content - I would just about this.  We have so many contexts to manage as it is

Whilst I have been known to use the term "project project" on occasions I dont see great levels of confusion day to day.

**Comment by githubbaxterwlane** [comment]
I kinda like project. Yes it is general and it took me awhile to wrap my mind around, but it makes perfect sense now. 

I'd stick with project.

**Comment by BenGGolden** [comment]
I don’t see anything wrong with Project. I think it’s better than the alternatives proposed so far and it would take something *much* better to make it worth the considerable effort to change.

**Comment by bakgaard** [comment]
Perhaps ``Project`` could be ``Domain`` instead? My understanding would be, that each current ``Project`` is something like ``https://myproject.com`` (main Project), ``https://proj2.myproject.com``, and ``https://proj3.myproject.com``.

**Comment by dsolovay** [comment]
No, no, no. So much pain. "You are still calling your project layer project? All the cool kids now call it..."

More seriously, I think the docs can do a better job of explaining the _role_ of each layer, which, at least to my understanding, is roughly: Foundation=Abstractions, Feature=Implementation, Project=Composition.  An analogy can even be made to the .NET concept of a project, which composes C# classses into an executable or a library; in much the same way, the Project layer composes features into a website. The other concerns of the Project layer, such as DI registration and feature to feature stitching (e.g. resolving one Feature's repository interface wiht date from another feature) can be understood as aspects of composition.

**Comment by alinulms** [comment]
If I remember correctly **Context** was the original name which makes absolute sense to me.

**Comment by anderslaub** [comment]
I always refer to the layer as **Context**. It is the layer where you compose your features into a specific **context**. (Composition could be a valid name as well - the composition layer. Compositions can be made on other layers as well just on a higher level of abstraction so I prefer **Context** for short and maybe the Context Composition layer in longer format). The original name was Project though, which I never thought made real sense because one project can have multiple contexts - or really none if the project relates to an existing. The name is the only layer name still inherited from the original Pentia component architecture.

**Comment by nickwesselman** [comment]
Going to close this for now, consensus seems to be that the change is not worth the pain. May revisit at a later date.
